package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"regexp"
	"strings"
	"text/template"
)

type Field struct {
	Name    string
	Type    string
	JSONTag string
	BSONTag string
	IsID    bool
	IsTime  bool
	IsSlice bool
	IsPtr   bool
}

type Config struct {
	Pkg        string
	Struct     string
	Collection string
	CreatedAt  string
	UpdatedAt  string
	CreatedTag string
	UpdatedTag string
	Fields     []Field
	Imports    []string
}

func toSnake(s string) string {
	re1 := regexp.MustCompile(`(.)([A-Z][a-z]+)`)
	re2 := regexp.MustCompile(`([a-z0-9])([A-Z])`)
	s = re1.ReplaceAllString(s, `${1}_${2}`)
	s = re2.ReplaceAllString(s, `${1}_${2}`)
	return strings.ToLower(s)
}

var repoTmpl = `
// Code generated by mongogen. DO NOT EDIT.
package {{.Pkg}}

import (
	"context"
{{if or .CreatedAt .UpdatedAt}}	"time"{{end}}

	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

type {{.Struct}}Repo struct {
	coll *mongo.Collection
}

func New{{.Struct}}Repo(db *mongo.Database) *{{.Struct}}Repo {
	return &{{.Struct}}Repo{coll: db.Collection("{{.Collection}}")}
}

// Create inserts a single {{.Struct}}
func (r *{{.Struct}}Repo) Create(ctx context.Context, dto *Create{{.Struct}}DTO, opts ...options.Lister[options.InsertOneOptions]) (*mongo.InsertOneResult, error) {
	m := dto.Model()
{{if or .CreatedAt .UpdatedAt}}	now := time.Now()
{{end}}{{if .CreatedAt}}	m.{{.CreatedAt}} = now
{{end}}{{if .UpdatedAt}}	m.{{.UpdatedAt}} = now
{{end}}	return r.coll.InsertOne(ctx, m, opts...)
}

// CreateMany inserts multiple {{.Struct}} documents
func (r *{{.Struct}}Repo) CreateMany(ctx context.Context, dtos []*Create{{.Struct}}DTO, opts ...options.Lister[options.InsertManyOptions]) (*mongo.InsertManyResult, error) {
{{if or .CreatedAt .UpdatedAt}}	now := time.Now()
{{end}}	models := make([]*{{.Struct}}, len(dtos))
	for i, dto := range dtos {
		models[i] = dto.Model()
{{if .CreatedAt}}		models[i].{{.CreatedAt}} = now
{{end}}{{if .UpdatedAt}}		models[i].{{.UpdatedAt}} = now
{{end}}	}
	return r.coll.InsertMany(ctx, models, opts...)
}

// FindByID retrieves a document by its _id
func (r *{{.Struct}}Repo) FindByID(ctx context.Context, id bson.ObjectID) (*{{.Struct}}, error) {
	var m {{.Struct}}
	if err := r.coll.FindOne(ctx, bson.M{"_id": id}).Decode(&m); err != nil {
		return nil, err
	}
	return &m, nil
}

// FindOne retrieves a single document matching the filter
func (r *{{.Struct}}Repo) FindOne(ctx context.Context, filter bson.M, opts ...options.Lister[options.FindOneOptions]) (*{{.Struct}}, error) {
	var m {{.Struct}}
	if err := r.coll.FindOne(ctx, filter, opts...).Decode(&m); err != nil {
		return nil, err
	}
	return &m, nil
}

// UpdateByID updates a document by ID using a DTO
func (r *{{.Struct}}Repo) UpdateByID(ctx context.Context, id bson.ObjectID, dto *Update{{.Struct}}DTO, opts ...options.Lister[options.UpdateOneOptions]) (*mongo.UpdateResult, error) {
	update := dto.BSON()
{{if .UpdatedAt}}	if update["$set"] == nil {
		update["$set"] = bson.M{}
	}
	update["$set"].(bson.M)["{{.UpdatedTag}}"] = time.Now()
{{end}}	return r.coll.UpdateOne(ctx, bson.M{"_id": id}, update, opts...)
}

// UpdateOne updates a single document matching the filter using a DTO
func (r *{{.Struct}}Repo) UpdateOne(ctx context.Context, filter bson.M, dto *Update{{.Struct}}DTO, opts ...options.Lister[options.UpdateOneOptions]) (*mongo.UpdateResult, error) {
	update := dto.BSON()
{{if .UpdatedAt}}	if update["$set"] == nil {
		update["$set"] = bson.M{}
	}
	update["$set"].(bson.M)["{{.UpdatedTag}}"] = time.Now()
{{end}}	return r.coll.UpdateOne(ctx, filter, update, opts...)
}

// UpdateMany updates multiple documents matching the filter using a DTO
func (r *{{.Struct}}Repo) UpdateMany(ctx context.Context, filter bson.M, dto *Update{{.Struct}}DTO, opts ...options.Lister[options.UpdateManyOptions]) (*mongo.UpdateResult, error) {
	update := dto.BSON()
{{if .UpdatedAt}}	if update["$set"] == nil {
		update["$set"] = bson.M{}
	}
	update["$set"].(bson.M)["{{.UpdatedTag}}"] = time.Now()
{{end}}	return r.coll.UpdateMany(ctx, filter, update, opts...)
}

// ReplaceOne replaces a single document matching the filter
func (r *{{.Struct}}Repo) ReplaceOne(ctx context.Context, filter bson.M, dto *Create{{.Struct}}DTO, opts ...options.Lister[options.ReplaceOptions]) (*mongo.UpdateResult, error) {
	m := dto.Model()
{{if or .CreatedAt .UpdatedAt}}	now := time.Now()
{{end}}{{if .CreatedAt}}	m.{{.CreatedAt}} = now
{{end}}{{if .UpdatedAt}}	m.{{.UpdatedAt}} = now
{{end}}	return r.coll.ReplaceOne(ctx, filter, m, opts...)
}

// DeleteByID removes a document by ID
func (r *{{.Struct}}Repo) DeleteByID(ctx context.Context, id bson.ObjectID, opts ...options.Lister[options.DeleteOneOptions]) (*mongo.DeleteResult, error) {
	return r.coll.DeleteOne(ctx, bson.M{"_id": id}, opts...)
}

// DeleteOne removes a single document matching the filter
func (r *{{.Struct}}Repo) DeleteOne(ctx context.Context, filter bson.M, opts ...options.Lister[options.DeleteOneOptions]) (*mongo.DeleteResult, error) {
	return r.coll.DeleteOne(ctx, filter, opts...)
}

// DeleteMany removes documents matching the filter
func (r *{{.Struct}}Repo) DeleteMany(ctx context.Context, filter bson.M, opts ...options.Lister[options.DeleteManyOptions]) (*mongo.DeleteResult, error) {
	return r.coll.DeleteMany(ctx, filter, opts...)
}

// FindOneAndUpdate performs an atomic find and update, returns updated document
func (r *{{.Struct}}Repo) FindOneAndUpdate(ctx context.Context, filter bson.M, dto *Update{{.Struct}}DTO, opts ...options.Lister[options.FindOneAndUpdateOptions]) (*{{.Struct}}, error) {
	update := dto.BSON()
{{if .UpdatedAt}}	if update["$set"] == nil {
		update["$set"] = bson.M{}
	}
	update["$set"].(bson.M)["{{.UpdatedTag}}"] = time.Now()
{{end}}	var m {{.Struct}}
	defOpts := options.FindOneAndUpdate().SetReturnDocument(options.After)
	allOpts := append([]options.Lister[options.FindOneAndUpdateOptions]{defOpts}, opts...)
	if err := r.coll.FindOneAndUpdate(ctx, filter, update, allOpts...).Decode(&m); err != nil {
		return nil, err
	}
	return &m, nil
}

// FindOneAndReplace performs an atomic find and replace, returns old document
func (r *{{.Struct}}Repo) FindOneAndReplace(ctx context.Context, filter bson.M, dto *Create{{.Struct}}DTO, opts ...options.Lister[options.FindOneAndReplaceOptions]) (*{{.Struct}}, error) {
	m := dto.Model()
{{if or .CreatedAt .UpdatedAt}}	now := time.Now()
{{end}}{{if .CreatedAt}}	m.{{.CreatedAt}} = now
{{end}}{{if .UpdatedAt}}	m.{{.UpdatedAt}} = now
{{end}}	var old {{.Struct}}
	defOpts := options.FindOneAndReplace().SetReturnDocument(options.Before)
	allOpts := append([]options.Lister[options.FindOneAndReplaceOptions]{defOpts}, opts...)
	if err := r.coll.FindOneAndReplace(ctx, filter, m, allOpts...).Decode(&old); err != nil {
		return nil, err
	}
	return &old, nil
}

// FindOneAndDelete performs an atomic find and delete, returns deleted document
func (r *{{.Struct}}Repo) FindOneAndDelete(ctx context.Context, filter bson.M, opts ...options.Lister[options.FindOneAndDeleteOptions]) (*{{.Struct}}, error) {
	var m {{.Struct}}
	if err := r.coll.FindOneAndDelete(ctx, filter, opts...).Decode(&m); err != nil {
		return nil, err
	}
	return &m, nil
}

// Upsert updates or creates a document by ID
func (r *{{.Struct}}Repo) Upsert(ctx context.Context, id bson.ObjectID, dto *Update{{.Struct}}DTO, opts ...options.Lister[options.UpdateOneOptions]) (*mongo.UpdateResult, error) {
	update := dto.BSON()
{{if or .CreatedAt .UpdatedAt}}	if update["$set"] == nil {
		update["$set"] = bson.M{}
	}
{{if .CreatedAt}}	if update["$setOnInsert"] == nil {
		update["$setOnInsert"] = bson.M{}
	}
	update["$setOnInsert"].(bson.M)["{{.CreatedTag}}"] = time.Now()
{{end}}{{if .UpdatedAt}}	update["$set"].(bson.M)["{{.UpdatedTag}}"] = time.Now()
{{end}}{{end}}	defOpts := options.UpdateOne().SetUpsert(true)
	allOpts := append([]options.Lister[options.UpdateOneOptions]{defOpts}, opts...)
	return r.coll.UpdateOne(ctx, bson.M{"_id": id}, update, allOpts...)
}

// UpsertOne upserts a single document matching the filter
func (r *{{.Struct}}Repo) UpsertOne(ctx context.Context, filter bson.M, dto *Update{{.Struct}}DTO, opts ...options.Lister[options.UpdateOneOptions]) (*mongo.UpdateResult, error) {
	update := dto.BSON()
{{if or .CreatedAt .UpdatedAt}}	if update["$set"] == nil {
		update["$set"] = bson.M{}
	}
{{if .CreatedAt}}	if update["$setOnInsert"] == nil {
		update["$setOnInsert"] = bson.M{}
	}
	update["$setOnInsert"].(bson.M)["{{.CreatedTag}}"] = time.Now()
{{end}}{{if .UpdatedAt}}	update["$set"].(bson.M)["{{.UpdatedTag}}"] = time.Now()
{{end}}{{end}}	defOpts := options.UpdateOne().SetUpsert(true)
	allOpts := append([]options.Lister[options.UpdateOneOptions]{defOpts}, opts...)
	return r.coll.UpdateOne(ctx, filter, update, allOpts...)
}

// Count returns the number of documents matching a filter
func (r *{{.Struct}}Repo) Count(ctx context.Context, filter bson.M) (int64, error) {
	return r.coll.CountDocuments(ctx, filter)
}

// Distinct finds unique values for a specified field
func (r *{{.Struct}}Repo) Distinct(ctx context.Context, field string, filter bson.M) (*mongo.DistinctResult, error) {
	res := r.coll.Distinct(ctx, field, filter)
	return res, res.Err()
}

// Exists checks if a document exists by ID
func (r *{{.Struct}}Repo) Exists(ctx context.Context, id bson.ObjectID) (bool, error) {
	count, err := r.coll.CountDocuments(ctx, bson.M{"_id": id}, options.Count().SetLimit(1))
	return count > 0, err
}

// BulkWrite performs multiple write operations in bulk
func (r *{{.Struct}}Repo) BulkWrite(ctx context.Context, models []mongo.WriteModel, opts ...options.Lister[options.BulkWriteOptions]) (*mongo.BulkWriteResult, error) {
	return r.coll.BulkWrite(ctx, models, opts...)
}

// FindAll retrieves all documents matching a filter
func (r *{{.Struct}}Repo) FindAll(ctx context.Context, filter bson.M) ([]*{{.Struct}}, error) {
	cur, err := r.coll.Find(ctx, filter)
	if err != nil {
		return nil, err
	}
	defer cur.Close(ctx)

	var results []*{{.Struct}}
	if err = cur.All(ctx, &results); err != nil {
		return nil, err
	}
	return results, nil
}

// Find returns a cursor for documents matching the filter
func (r *{{.Struct}}Repo) Find(ctx context.Context, filter bson.M, opts ...options.Lister[options.FindOptions]) (*mongo.Cursor, error) {
	return r.coll.Find(ctx, filter, opts...)
}

// FindPage retrieves a page of documents with sorting
func (r *{{.Struct}}Repo) FindPage(ctx context.Context, filter bson.M, page, limit int64, sort bson.D, opts ...options.Lister[options.FindOptions]) ([]*{{.Struct}}, int64, error) {
	skip := (page - 1) * limit
	if skip < 0 {
		skip = 0
	}

	total, err := r.coll.CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, err
	}

	defOpts := options.Find().SetLimit(limit).SetSkip(skip).SetSort(sort)
	allOpts := append([]options.Lister[options.FindOptions]{defOpts}, opts...)

	cur, err := r.coll.Find(ctx, filter, allOpts...)
	if err != nil {
		return nil, 0, err
	}
	defer cur.Close(ctx)

	var results []*{{.Struct}}
	if err = cur.All(ctx, &results); err != nil {
		return nil, 0, err
	}
	return results, total, nil
}

// Aggregate runs an aggregation pipeline
func (r *{{.Struct}}Repo) Aggregate(ctx context.Context, pipeline mongo.Pipeline) (*mongo.Cursor, error) {
	return r.coll.Aggregate(ctx, pipeline)
}

// Watch creates a change stream
func (r *{{.Struct}}Repo) Watch(ctx context.Context, pipeline mongo.Pipeline) (*mongo.ChangeStream, error) {
	return r.coll.Watch(ctx, pipeline)
}

// Coll returns the underlying mongo collection
func (r *{{.Struct}}Repo) Coll() *mongo.Collection {
	return r.coll
}
`

var dtoTmpl = `
// Code generated by mongogen. DO NOT EDIT.
package {{.Pkg}}

import (
{{if or .CreatedAt .UpdatedAt}}	"time"
{{end}}{{range .Imports}}	"{{.}}"
{{end}}
	"go.mongodb.org/mongo-driver/v2/bson"
)

type Create{{.Struct}}DTO struct {
{{range .Fields}}{{if not (or .IsID (eq .Name $.CreatedAt) (eq .Name $.UpdatedAt))}}	{{.Name}} {{.Type}} ` + "`" + `json:"{{.JSONTag}}" bson:"{{.BSONTag}}"` + "`" + `
{{end}}{{end}}}

type Update{{.Struct}}DTO struct {
{{range .Fields}}{{if not (or .IsID (eq .Name $.CreatedAt) (eq .Name $.UpdatedAt))}}	{{.Name}} {{if not .IsPtr}}*{{end}}{{.Type}} ` + "`" + `json:"{{.JSONTag}},omitempty" bson:"{{.BSONTag}},omitempty"` + "`" + `
{{end}}{{end}}}

type {{.Struct}}Response struct {
{{range .Fields}}	{{.Name}} {{.Type}} ` + "`" + `json:"{{.JSONTag}}" bson:"{{.BSONTag}}"` + "`" + `
{{end}}}

func (dto *Create{{.Struct}}DTO) Model() *{{.Struct}} {
	return &{{.Struct}}{
{{range .Fields}}{{if not (or .IsID (eq .Name $.CreatedAt) (eq .Name $.UpdatedAt))}}		{{.Name}}: dto.{{.Name}},
{{end}}{{end}}	}
}

func (dto *Update{{.Struct}}DTO) BSON() bson.M {
	set := bson.M{}
{{range .Fields}}{{if not (or .IsID (eq .Name $.CreatedAt) (eq .Name $.UpdatedAt))}}	if dto.{{.Name}} != nil {
		set["{{.BSONTag}}"] = {{if not .IsPtr}}*{{end}}dto.{{.Name}}
	}
{{end}}{{end}}	if len(set) == 0 {
		return bson.M{}
	}
	return bson.M{"$set": set}
}

func (m *{{.Struct}}) Response() *{{.Struct}}Response {
	return &{{.Struct}}Response{
{{range .Fields}}		{{.Name}}: m.{{.Name}},
{{end}}	}
}

func {{.Struct}}Responses(models []*{{.Struct}}) []*{{.Struct}}Response {
	res := make([]*{{.Struct}}Response, len(models))
	for i, m := range models {
		res[i] = m.Response()
	}
	return res
}
`

func extractImportPath(typeStr string) string {
	// Check if type contains a package selector (e.g., "time.Time" or "common.Something")
	if idx := strings.Index(typeStr, "."); idx > 0 {
		pkgName := typeStr[:idx]
		// Skip built-in types that don't need imports
		if pkgName == "time" {
			return ""
		}
		return pkgName
	}
	return ""
}

func collectImports(fields []Field, imports map[string]bool) {
	for _, field := range fields {
		// Remove pointer and slice prefixes to get base type
		baseType := field.Type
		baseType = strings.TrimPrefix(baseType, "*")
		baseType = strings.TrimPrefix(baseType, "[]")

		// Check if type contains a package path
		if strings.Contains(baseType, ".") {
			// Handle selector expressions like "time.Time" or "common.Status"
			parts := strings.Split(baseType, ".")
			if len(parts) >= 2 {
				pkgPath := strings.Join(parts[:len(parts)-1], ".")
				// Skip standard library packages that are already imported
				if pkgPath != "time" && pkgPath != "bson" {
					imports[pkgPath] = true
				}
			}
		}
	}
}

func fieldType(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + fieldType(t.X)
	case *ast.ArrayType:
		return "[]" + fieldType(t.Elt)
	case *ast.SelectorExpr:
		return fieldType(t.X) + "." + t.Sel.Name
	case *ast.MapType:
		return "map[" + fieldType(t.Key) + "]" + fieldType(t.Value)
	default:
		return "interface{}"
	}
}

func parseTag(f *ast.Field, name string) string {
	if f.Tag == nil {
		return ""
	}
	tag := strings.Trim(f.Tag.Value, "`")
	for part := range strings.FieldsSeq(tag) {
		val, ok := strings.CutPrefix(part, name+":")
		if !ok {
			continue
		}
		val = strings.Trim(val, "\"")
		before, _, found := strings.Cut(val, ",")
		if found {
			return before
		}
		return val
	}
	return ""
}

func collectFileImports(f *ast.File) map[string]string {
	// Map from package name to import path
	imports := make(map[string]string)
	for _, imp := range f.Imports {
		path := strings.Trim(imp.Path.Value, "\"")
		var name string
		if imp.Name != nil {
			name = imp.Name.Name
		} else {
			// Extract package name from path
			parts := strings.Split(path, "/")
			name = parts[len(parts)-1]
		}
		imports[name] = path
	}
	return imports
}

func main() {
	typ := flag.String("type", "", "struct name to generate code for")
	coll := flag.String("collection", "", "mongodb collection name (defaults to lowercase struct + 's')")
	flag.Parse()

	if *typ == "" {
		log.Fatal("type argument is required")
	}

	if ok, err := regexp.MatchString(`^[a-zA-Z_][a-zA-Z0-9_]*$`, *typ); err != nil || !ok {
		log.Fatal("type must be a valid Go identifier")
	}

	pkg := os.Getenv("GOPACKAGE")
	if pkg == "" {
		log.Fatal("GOPACKAGE environment variable not set")
	}

	collection := *coll
	if collection == "" {
		collection = strings.ToLower(*typ) + "s"
	}

	var createdAt, updatedAt, createdTag, updatedTag string
	var fields []Field
	var fileImports map[string]string
	fset := token.NewFileSet()

	entries, err := os.ReadDir(".")
	if err != nil {
		log.Fatalf("failed to read directory: %v", err)
	}
	found := false

	// If GOFILE is set, parse that file directly first
	goFile := os.Getenv("GOFILE")
	if goFile != "" {
		f, parseErr := parser.ParseFile(fset, goFile, nil, parser.ParseComments)
		if parseErr == nil {
			fileImports = collectFileImports(f)
			ast.Inspect(f, func(n ast.Node) bool {
				ts, ok := n.(*ast.TypeSpec)
				if !ok || ts.Name.Name != *typ {
					return true
				}

				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					return true
				}

				for _, field := range st.Fields.List {
					for _, name := range field.Names {
						lower := strings.ToLower(strings.ReplaceAll(name.Name, "_", ""))
						ft := fieldType(field.Type)
						jsonTag := parseTag(field, "json")
						bsonTag := parseTag(field, "bson")

						if lower == "createdat" {
							createdAt = name.Name
							createdTag = bsonTag
							if createdTag == "" {
								createdTag = jsonTag
							}
						}
						if lower == "updatedat" {
							updatedAt = name.Name
							updatedTag = bsonTag
							if updatedTag == "" {
								updatedTag = jsonTag
							}
						}

						if jsonTag == "" {
							jsonTag = toSnake(name.Name)
						}
						if bsonTag == "" {
							bsonTag = toSnake(name.Name)
						}

						fields = append(fields, Field{
							Name:    name.Name,
							Type:    ft,
							JSONTag: jsonTag,
							BSONTag: bsonTag,
							IsID:    bsonTag == "_id" || lower == "id",
							IsTime:  strings.Contains(ft, "time.Time"),
							IsSlice: strings.HasPrefix(ft, "[]"),
							IsPtr:   strings.HasPrefix(ft, "*"),
						})
					}
				}
				found = true
				return false
			})
		}
	}

	// If not found yet, scan all files in the target directory
	if !found {
		for _, entry := range entries {
			if found {
				break
			}
			if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
				continue
			}
			if strings.HasPrefix(entry.Name(), ".") || strings.HasPrefix(entry.Name(), "_") {
				continue
			}

			f, parseErr := parser.ParseFile(fset, entry.Name(), nil, parser.ParseComments)
			if parseErr != nil {
				continue
			}

			fileImports = collectFileImports(f)
			ast.Inspect(f, func(n ast.Node) bool {
				ts, ok := n.(*ast.TypeSpec)
				if !ok || ts.Name.Name != *typ {
					return true
				}

				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					return true
				}

				for _, field := range st.Fields.List {
					for _, name := range field.Names {
						lower := strings.ToLower(strings.ReplaceAll(name.Name, "_", ""))
						ft := fieldType(field.Type)
						jsonTag := parseTag(field, "json")
						bsonTag := parseTag(field, "bson")

						if lower == "createdat" {
							createdAt = name.Name
							createdTag = bsonTag
							if createdTag == "" {
								createdTag = jsonTag
							}
						}
						if lower == "updatedat" {
							updatedAt = name.Name
							updatedTag = bsonTag
							if updatedTag == "" {
								updatedTag = jsonTag
							}
						}

						if jsonTag == "" {
							jsonTag = toSnake(name.Name)
						}
						if bsonTag == "" {
							bsonTag = toSnake(name.Name)
						}

						fields = append(fields, Field{
							Name:    name.Name,
							Type:    ft,
							JSONTag: jsonTag,
							BSONTag: bsonTag,
							IsID:    bsonTag == "_id" || lower == "id",
							IsTime:  strings.Contains(ft, "time.Time"),
							IsSlice: strings.HasPrefix(ft, "[]"),
							IsPtr:   strings.HasPrefix(ft, "*"),
						})
					}
				}
				found = true
				return false
			})
		}
	}

	// Collect imports needed for field types
	importPaths := make(map[string]bool)
	collectImports(fields, importPaths)

	// Convert package names to full import paths using fileImports
	var imports []string
	for pkgName := range importPaths {
		if fullPath, ok := fileImports[pkgName]; ok {
			imports = append(imports, fullPath)
		}
	}

	cfg := Config{
		Pkg:        pkg,
		Struct:     *typ,
		Collection: collection,
		CreatedAt:  createdAt,
		UpdatedAt:  updatedAt,
		CreatedTag: createdTag,
		UpdatedTag: updatedTag,
		Fields:     fields,
		Imports:    imports,
	}

	// Generate repository
	tmpl := template.Must(template.New("repo").Parse(repoTmpl))
	var buf bytes.Buffer
	if execErr := tmpl.Execute(&buf, cfg); execErr != nil {
		log.Fatal(execErr)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("formatting error: %s", err)
	}

	filename := fmt.Sprintf("repo.go")
	if err := os.WriteFile(filename, formatted, 0644); err != nil {
		log.Fatal(err)
	}

	fmt.Printf("Generated %s for struct %s\n", filename, *typ)

	// Generate DTOs
	if len(fields) > 0 {
		tmpl := template.Must(template.New("dto").Parse(dtoTmpl))
		var buf bytes.Buffer
		if err := tmpl.Execute(&buf, cfg); err != nil {
			log.Fatal(err)
		}

		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			log.Fatalf("dto formatting error: %s", err)
		}

		filename := fmt.Sprintf("dto.go")
		if err := os.WriteFile(filename, formatted, 0644); err != nil {
			log.Fatal(err)
		}

		fmt.Printf("Generated %s for struct %s\n", filename, *typ)
	}
}
