package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"regexp"
	"strings"
	"text/template"
)

// Config holds the data used to populate the template
type Config struct {
	PackageName    string
	StructName     string
	TableName      string
	CreatedAtField string
	UpdatedAtField string
}

func toSnakeCase(s string) string {
	matchFirstCap := regexp.MustCompile(`(.)([A-Z][a-z]+)`)
	matchAllCap := regexp.MustCompile(`([a-z0-9])([A-Z])`)

	snake := matchFirstCap.ReplaceAllString(s, `${1}_${2}`)
	snake = matchAllCap.ReplaceAllString(snake, `${1}_${2}`)
	return strings.ToLower(snake)
}

var outputTemplate = `
// Code generated by mongogen. DO NOT EDIT.
package {{.PackageName}}

import (
	"context"
{{if or .CreatedAtField .UpdatedAtField}}	"time"{{end}}

	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

// {{.StructName}}Repository defines strict repository methods
type {{.StructName}}Repository struct {
	collection *mongo.Collection
}

// New{{.StructName}}Repository creates a new repository instance
func New{{.StructName}}Repository(db *mongo.Database) *{{.StructName}}Repository {
	return &{{.StructName}}Repository{
		collection: db.Collection("{{.TableName}}"),
	}
}

// --- Basic CRUD ---

// Create inserts a single {{.StructName}}
func (r *{{.StructName}}Repository) Create(ctx context.Context, model *{{.StructName}}, opts ...options.Lister[options.InsertOneOptions]) (*mongo.InsertOneResult, error) {
{{if .CreatedAtField}}	model.{{.CreatedAtField}} = time.Now()
{{end}}{{if .UpdatedAtField}}	model.{{.UpdatedAtField}} = time.Now()
{{end}}	return r.collection.InsertOne(ctx, model, opts...)
}

// CreateMany inserts multiple {{.StructName}} documents
func (r *{{.StructName}}Repository) CreateMany(ctx context.Context, models []*{{.StructName}}, opts ...options.Lister[options.InsertManyOptions]) (*mongo.InsertManyResult, error) {
{{if or .CreatedAtField .UpdatedAtField}}	now := time.Now()
	for _, model := range models {
{{if .CreatedAtField}}		model.{{.CreatedAtField}} = now{{end}}
{{if .UpdatedAtField}}		model.{{.UpdatedAtField}} = now{{end}}
	}
{{end}}	return r.collection.InsertMany(ctx, models, opts...)
}

// FindByID retrieves a document by its _id
func (r *{{.StructName}}Repository) FindByID(ctx context.Context, id bson.ObjectID) (*{{.StructName}}, error) {
	var model {{.StructName}}
	err := r.collection.FindOne(ctx, bson.M{"_id": id}).Decode(&model)
	if err != nil {
		return nil, err
	}
	return &model, nil
}

// FindOne retrieves a single document matching the filter
func (r *{{.StructName}}Repository) FindOne(ctx context.Context, filter bson.M, opts ...options.Lister[options.FindOneOptions]) (*{{.StructName}}, error) {
	var model {{.StructName}}
	err := r.collection.FindOne(ctx, filter, opts...).Decode(&model)
	if err != nil {
		return nil, err
	}
	return &model, nil
}

// UpdateByID updates a document by ID using the full update bson map (e.g., bson.M{"$set": fields} or bson.M{"$inc": ...})
func (r *{{.StructName}}Repository) UpdateByID(ctx context.Context, id bson.ObjectID, update bson.M, opts ...options.Lister[options.UpdateOneOptions]) (*mongo.UpdateResult, error) {
{{if .UpdatedAtField}}	// Ensure UpdatedAt is set
	if _, ok := update["$set"]; !ok {
		update["$set"] = bson.M{}
	}
	if setMap, ok := update["$set"].(bson.M); ok {
		setMap["updated_at"] = time.Now()
	}
{{end}}	return r.collection.UpdateOne(ctx, bson.M{"_id": id}, update, opts...)
}

// UpdateOne updates a single document matching the filter using the full update bson map
func (r *{{.StructName}}Repository) UpdateOne(ctx context.Context, filter bson.M, update bson.M, opts ...options.Lister[options.UpdateOneOptions]) (*mongo.UpdateResult, error) {
{{if .UpdatedAtField}}	// Ensure UpdatedAt is set
	if _, ok := update["$set"]; !ok {
		update["$set"] = bson.M{}
	}
	if setMap, ok := update["$set"].(bson.M); ok {
		setMap["updated_at"] = time.Now()
	}
{{end}}	return r.collection.UpdateOne(ctx, filter, update, opts...)
}

// UpdateMany updates multiple documents matching the filter using the full update bson map
func (r *{{.StructName}}Repository) UpdateMany(ctx context.Context, filter bson.M, update bson.M, opts ...options.Lister[options.UpdateManyOptions]) (*mongo.UpdateResult, error) {
{{if .UpdatedAtField}}	// Ensure UpdatedAt is set
	if _, ok := update["$set"]; !ok {
		update["$set"] = bson.M{}
	}
	if setMap, ok := update["$set"].(bson.M); ok {
		setMap["updated_at"] = time.Now()
	}
{{end}}	return r.collection.UpdateMany(ctx, filter, update, opts...)
}

// ReplaceOne replaces a single document matching the filter with the provided replacement
func (r *{{.StructName}}Repository) ReplaceOne(ctx context.Context, filter bson.M, replacement *{{.StructName}}, opts ...options.Lister[options.ReplaceOptions]) (*mongo.UpdateResult, error) {
{{if .UpdatedAtField}}	replacement.{{.UpdatedAtField}} = time.Now()
{{end}}	return r.collection.ReplaceOne(ctx, filter, replacement, opts...)
}

// DeleteByID removes a document by ID
func (r *{{.StructName}}Repository) DeleteByID(ctx context.Context, id bson.ObjectID, opts ...options.Lister[options.DeleteOneOptions]) (*mongo.DeleteResult, error) {
	return r.collection.DeleteOne(ctx, bson.M{"_id": id}, opts...)
}

// DeleteOne removes a single document matching the filter
func (r *{{.StructName}}Repository) DeleteOne(ctx context.Context, filter bson.M, opts ...options.Lister[options.DeleteOneOptions]) (*mongo.DeleteResult, error) {
	return r.collection.DeleteOne(ctx, filter, opts...)
}

// DeleteMany removes documents matching the filter
func (r *{{.StructName}}Repository) DeleteMany(ctx context.Context, filter bson.M, opts ...options.Lister[options.DeleteManyOptions]) (*mongo.DeleteResult, error) {
	return r.collection.DeleteMany(ctx, filter, opts...)
}

// --- Advanced Operations ---

// FindOneAndUpdate performs an atomic find and update operation
// Returns the *updated* document (ReturnDocument: After)
// update is the full update document, e.g., bson.M{"$set": fields} or bson.M{"$inc": ...}
func (r *{{.StructName}}Repository) FindOneAndUpdate(ctx context.Context, filter bson.M, update bson.M, opts ...options.Lister[options.FindOneAndUpdateOptions]) (*{{.StructName}}, error) {
	var model {{.StructName}}
	defaultOpts := options.FindOneAndUpdate().SetReturnDocument(options.After)
	combinedOpts := append([]options.Lister[options.FindOneAndUpdateOptions]{defaultOpts}, opts...)

	err := r.collection.FindOneAndUpdate(ctx, filter, update, combinedOpts...).Decode(&model)
	if err != nil {
		return nil, err
	}
	return &model, nil
}

// FindOneAndReplace performs an atomic find and replace operation
// Returns the *replaced* document (ReturnDocument: Before)
func (r *{{.StructName}}Repository) FindOneAndReplace(ctx context.Context, filter bson.M, replacement *{{.StructName}}, opts ...options.Lister[options.FindOneAndReplaceOptions]) (*{{.StructName}}, error) {
{{if .UpdatedAtField}}	replacement.{{.UpdatedAtField}} = time.Now()
{{end}}	var model {{.StructName}}
	defaultOpts := options.FindOneAndReplace().SetReturnDocument(options.Before)
	combinedOpts := append([]options.Lister[options.FindOneAndReplaceOptions]{defaultOpts}, opts...)

	err := r.collection.FindOneAndReplace(ctx, filter, replacement, combinedOpts...).Decode(&model)
	if err != nil {
		return nil, err
	}
	return &model, nil
}

// FindOneAndDelete performs an atomic find and delete operation
// Returns the *deleted* document
func (r *{{.StructName}}Repository) FindOneAndDelete(ctx context.Context, filter bson.M, opts ...options.Lister[options.FindOneAndDeleteOptions]) (*{{.StructName}}, error) {
	var model {{.StructName}}
	err := r.collection.FindOneAndDelete(ctx, filter, opts...).Decode(&model)
	if err != nil {
		return nil, err
	}
	return &model, nil
}

// Upsert updates a document if it exists, or creates it if it doesn't
// update is the full update document, e.g., bson.M{"$set": fields} or bson.M{"$inc": ...}
func (r *{{.StructName}}Repository) Upsert(ctx context.Context, id bson.ObjectID, update bson.M, opts ...options.Lister[options.UpdateOneOptions]) (*mongo.UpdateResult, error) {
{{if or .CreatedAtField .UpdatedAtField}}	// Ensure timestamps are set
	if _, ok := update["$set"]; !ok {
		update["$set"] = bson.M{}
	}
	if setMap, ok := update["$set"].(bson.M); ok {
{{if .CreatedAtField}}		// Set CreatedAt only on insert using $setOnInsert
		if _, ok := update["$setOnInsert"]; !ok {
			update["$setOnInsert"] = bson.M{}
		}
		if setOnInsertMap, ok := update["$setOnInsert"].(bson.M); ok {
			setOnInsertMap["created_at"] = time.Now()
		}
{{end}}{{if .UpdatedAtField}}		setMap["updated_at"] = time.Now()
{{end}}	}
{{end}}	defaultOpts := options.UpdateOne().SetUpsert(true)
	combinedOpts := append([]options.Lister[options.UpdateOneOptions]{defaultOpts}, opts...)
	return r.collection.UpdateOne(ctx, bson.M{"_id": id}, update, combinedOpts...)
}

// UpsertOne upserts a single document matching the filter
func (r *{{.StructName}}Repository) UpsertOne(ctx context.Context, filter bson.M, update bson.M, opts ...options.Lister[options.UpdateOneOptions]) (*mongo.UpdateResult, error) {
{{if or .CreatedAtField .UpdatedAtField}}	// Ensure timestamps are set
	if _, ok := update["$set"]; !ok {
		update["$set"] = bson.M{}
	}
	if setMap, ok := update["$set"].(bson.M); ok {
{{if .CreatedAtField}}		// Set CreatedAt only on insert using $setOnInsert
		if _, ok := update["$setOnInsert"]; !ok {
			update["$setOnInsert"] = bson.M{}
		}
		if setOnInsertMap, ok := update["$setOnInsert"].(bson.M); ok {
			setOnInsertMap["created_at"] = time.Now()
		}
{{end}}{{if .UpdatedAtField}}		setMap["updated_at"] = time.Now()
{{end}}	}
{{end}}	defaultOpts := options.UpdateOne().SetUpsert(true)
	combinedOpts := append([]options.Lister[options.UpdateOneOptions]{defaultOpts}, opts...)
	return r.collection.UpdateOne(ctx, filter, update, combinedOpts...)
}

// Count returns the number of documents matching a filter
func (r *{{.StructName}}Repository) Count(ctx context.Context, filter bson.M) (int64, error) {
	return r.collection.CountDocuments(ctx, filter)
}

// Distinct finds unique values for a specified field
func (r *{{.StructName}}Repository) Distinct(ctx context.Context, fieldName string, filter bson.M) (*mongo.DistinctResult, error) {
	res := r.collection.Distinct(ctx, fieldName, filter)
	return res, res.Err()
}

// Exists checks if a document exists by ID
func (r *{{.StructName}}Repository) Exists(ctx context.Context, id bson.ObjectID) (bool, error) {
	count, err := r.collection.CountDocuments(ctx, bson.M{"_id": id}, options.Count().SetLimit(1))
	return count > 0, err
}

// BulkWrite performs multiple write operations in bulk
func (r *{{.StructName}}Repository) BulkWrite(ctx context.Context, models []mongo.WriteModel, opts ...options.Lister[options.BulkWriteOptions]) (*mongo.BulkWriteResult, error) {
	return r.collection.BulkWrite(ctx, models, opts...)
}

// --- Search, Pagination & Aggregation ---

// FindAll retrieves all documents matching a filter
func (r *{{.StructName}}Repository) FindAll(ctx context.Context, filter bson.M, opts ...options.Lister[options.FindOptions]) ([]*{{.StructName}}, error) {
	cursor, err := r.collection.Find(ctx, filter, opts...)
	if err != nil {
		return nil, err
	}
	defer cursor.Close(ctx)

	var results []*{{.StructName}}
	if err = cursor.All(ctx, &results); err != nil {
		return nil, err
	}
	return results, nil
}

// Find returns a cursor for documents matching the filter
func (r *{{.StructName}}Repository) Find(ctx context.Context, filter bson.M, opts ...options.Lister[options.FindOptions]) (*mongo.Cursor, error) {
	return r.collection.Find(ctx, filter, opts...)
}

// FindPage retrieves a page of documents with sorting options
func (r *{{.StructName}}Repository) FindPage(ctx context.Context, filter bson.M, page int64, limit int64, sort bson.D, opts ...options.Lister[options.FindOptions]) ([]*{{.StructName}}, int64, error) {
	skip := (page - 1) * limit
	if skip < 0 {
		skip = 0
	}

	total, err := r.collection.CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, err
	}

	defaultOpts := options.Find().SetLimit(limit).SetSkip(skip).SetSort(sort)
	combinedOpts := append([]options.Lister[options.FindOptions]{defaultOpts}, opts...)

	cursor, err := r.collection.Find(ctx, filter, combinedOpts...)
	if err != nil {
		return nil, 0, err
	}
	defer cursor.Close(ctx)

	var results []*{{.StructName}}
	if err = cursor.All(ctx, &results); err != nil {
		return nil, 0, err
	}
	return results, total, nil
}

// Aggregate runs a raw aggregation pipeline
// Note: This returns a cursor because aggregation results usually do not match the {{.StructName}} structure.
// You must decode the cursor into your specific result struct.
func (r *{{.StructName}}Repository) Aggregate(ctx context.Context, pipeline mongo.Pipeline) (*mongo.Cursor, error) {
	return r.collection.Aggregate(ctx, pipeline)
}

// Watch creates a change stream to listen for real-time updates on this collection
func (r *{{.StructName}}Repository) Watch(ctx context.Context, pipeline mongo.Pipeline) (*mongo.ChangeStream, error) {
	return r.collection.Watch(ctx, pipeline)
}

// Collection returns the underlying mongo collection for advanced operations
func (r *{{.StructName}}Repository) Collection() *mongo.Collection {
	return r.collection
}
`

func main() {
	typePtr := flag.String("type", "", "The struct name to generate code for")
	collectionPtr := flag.String("collection", "", "The mongodb collection name (optional, defaults to lowercase struct name)")
	packagePtr := flag.String("package", "", "The package directory to generate code in (optional, defaults to current directory)")
	flag.Parse()

	if *typePtr == "" {
		log.Fatal("type argument is required")
	}

	if matched, err := regexp.MatchString(`^[a-zA-Z_][a-zA-Z0-9_]*$`, *typePtr); err != nil || !matched {
		log.Fatal("type must be a valid Go identifier")
	}

	// go generate sets the GOPACKAGE environment variable to the package name of the file that contains the generate directive.
	// We use this to ensure the generated code is in the correct package.
	pkg := os.Getenv("GOPACKAGE")
	if pkg == "" {
		log.Fatal("GOPACKAGE environment variable not set")
	}

	// go generate also sets GOFILE to the file name that contains the generate directive
	goFile := os.Getenv("GOFILE")

	col := *collectionPtr
	if col == "" {
		col = strings.ToLower(*typePtr) + "s"
	}

	// Determine the target directory for generated code
	targetDir := "."
	if *packagePtr != "" {
		targetDir = *packagePtr
	}

	// We need to parse the source file to find the struct definition.
	// This allows us to inspect the struct fields and automatically handle fields like CreatedAt and UpdatedAt.
	var createdAtField, updatedAtField string

	// If GOFILE is set, we know exactly which file invoked go generate
	if goFile != "" {
		fset := token.NewFileSet()
		f, err := parser.ParseFile(fset, goFile, nil, 0)
		if err == nil {
			// Traverse the AST to find the struct type specification matching the requested type name
			ast.Inspect(f, func(n ast.Node) bool {
				if t, ok := n.(*ast.TypeSpec); ok {
					if t.Name.Name == *typePtr {
						// Struct found, inspect fields
						if st, ok := t.Type.(*ast.StructType); ok {
							for _, field := range st.Fields.List {
								for _, name := range field.Names {
									lower := strings.ToLower(strings.ReplaceAll(name.Name, "_", ""))
									if lower == "createdat" {
										createdAtField = name.Name
									}
									if lower == "updatedat" {
										updatedAtField = name.Name
									}
								}
							}
						}
						return false // Stop traversal
					}
				}
				return true
			})
		}
	}

	config := Config{
		PackageName:    pkg,
		StructName:     *typePtr,
		TableName:      col,
		CreatedAtField: createdAtField,
		UpdatedAtField: updatedAtField,
	}

	t, err := template.New("mongo").Parse(outputTemplate)
	if err != nil {
		log.Fatal(err)
	}

	var buf bytes.Buffer
	err = t.Execute(&buf, config)
	if err != nil {
		log.Fatal(err)
	}

	// Run gofmt on the generated code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("formatting error: %s", err)
	}

	filename := fmt.Sprintf("%s/%s_mongo.go", targetDir, toSnakeCase(*typePtr))
	err = os.WriteFile(filename, formatted, 0644)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("Generated %s for struct %s\n", filename, *typePtr)
}
