// Code generated by mongogen. DO NOT EDIT.
package model

import (
	"context"

	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

// LastRunRepository defines strict repository methods
type LastRunRepository struct {
	collection *mongo.Collection
}

// NewLastRunRepository creates a new repository instance
func NewLastRunRepository(db *mongo.Database) *LastRunRepository {
	return &LastRunRepository{
		collection: db.Collection("last_runs"),
	}
}

// --- Basic CRUD ---

// Create inserts a single LastRun
func (r *LastRunRepository) Create(ctx context.Context, model *LastRun) (*mongo.InsertOneResult, error) {
	return r.collection.InsertOne(ctx, model)
}

// CreateMany inserts multiple LastRun documents
func (r *LastRunRepository) CreateMany(ctx context.Context, models []*LastRun, opts ...options.Lister[options.InsertManyOptions]) (*mongo.InsertManyResult, error) {
	return r.collection.InsertMany(ctx, models, opts...)
}

// FindByID retrieves a document by its _id
func (r *LastRunRepository) FindByID(ctx context.Context, id primitive.ObjectID) (*LastRun, error) {
	var model LastRun
	err := r.collection.FindOne(ctx, bson.M{"_id": id}).Decode(&model)
	if err != nil {
		return nil, err
	}
	return &model, nil
}

// FindOne retrieves a single document matching the filter
func (r *LastRunRepository) FindOne(ctx context.Context, filter bson.M) (*LastRun, error) {
	var model LastRun
	err := r.collection.FindOne(ctx, filter).Decode(&model)
	if err != nil {
		return nil, err
	}
	return &model, nil
}

// UpdateByID updates a document by ID using the full update bson map (e.g., bson.M{"$set": fields} or bson.M{"$inc": ...})
func (r *LastRunRepository) UpdateByID(ctx context.Context, id primitive.ObjectID, update bson.M) (*mongo.UpdateResult, error) {
	return r.collection.UpdateOne(ctx, bson.M{"_id": id}, update)
}

// UpdateMany updates multiple documents matching the filter using the full update bson map
func (r *LastRunRepository) UpdateMany(ctx context.Context, filter bson.M, update bson.M) (*mongo.UpdateResult, error) {
	return r.collection.UpdateMany(ctx, filter, update)
}

// DeleteByID removes a document by ID
func (r *LastRunRepository) DeleteByID(ctx context.Context, id primitive.ObjectID) (*mongo.DeleteResult, error) {
	return r.collection.DeleteOne(ctx, bson.M{"_id": id})
}

// DeleteMany removes documents matching the filter
func (r *LastRunRepository) DeleteMany(ctx context.Context, filter bson.M) (*mongo.DeleteResult, error) {
	return r.collection.DeleteMany(ctx, filter)
}

// --- Advanced Operations ---

// FindOneAndUpdate performs an atomic find and update operation
// Returns the *updated* document (ReturnDocument: After)
// update is the full update document, e.g., bson.M{"$set": fields} or bson.M{"$inc": ...}
func (r *LastRunRepository) FindOneAndUpdate(ctx context.Context, filter bson.M, update bson.M) (*LastRun, error) {
	var model LastRun
	opts := options.FindOneAndUpdate().SetReturnDocument(options.After)

	err := r.collection.FindOneAndUpdate(ctx, filter, update, opts).Decode(&model)
	if err != nil {
		return nil, err
	}
	return &model, nil
}

// Upsert updates a document if it exists, or creates it if it doesn't
// update is the full update document, e.g., bson.M{"$set": fields} or bson.M{"$inc": ...}
func (r *LastRunRepository) Upsert(ctx context.Context, id primitive.ObjectID, update bson.M) (*mongo.UpdateResult, error) {
	opts := options.UpdateOne().SetUpsert(true)
	return r.collection.UpdateOne(ctx, bson.M{"_id": id}, update, opts)
}

// Count returns the number of documents matching a filter
func (r *LastRunRepository) Count(ctx context.Context, filter bson.M) (int64, error) {
	return r.collection.CountDocuments(ctx, filter)
}

// Distinct finds unique values for a specified field
func (r *LastRunRepository) Distinct(ctx context.Context, fieldName string, filter bson.M) (*mongo.DistinctResult, error) {
	res := r.collection.Distinct(ctx, fieldName, filter)
	return res, res.Err()
}

// --- Search, Pagination & Aggregation ---

// FindAll retrieves all documents matching a filter
func (r *LastRunRepository) FindAll(ctx context.Context, filter bson.M) ([]*LastRun, error) {
	cursor, err := r.collection.Find(ctx, filter)
	if err != nil {
		return nil, err
	}
	defer cursor.Close(ctx)

	var results []*LastRun
	if err = cursor.All(ctx, &results); err != nil {
		return nil, err
	}
	return results, nil
}

// FindPage retrieves a page of documents with sorting options
func (r *LastRunRepository) FindPage(ctx context.Context, filter bson.M, page int64, limit int64, sort interface{}) ([]*LastRun, int64, error) {
	skip := (page - 1) * limit
	if skip < 0 {
		skip = 0
	}

	total, err := r.collection.CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, err
	}

	opts := options.Find().SetLimit(limit).SetSkip(skip).SetSort(sort)
	cursor, err := r.collection.Find(ctx, filter, opts)
	if err != nil {
		return nil, 0, err
	}
	defer cursor.Close(ctx)

	var results []*LastRun
	if err = cursor.All(ctx, &results); err != nil {
		return nil, 0, err
	}
	return results, total, nil
}

// Aggregate runs a raw aggregation pipeline
// Note: This returns a cursor because aggregation results usually do not match the LastRun structure.
// You must decode the cursor into your specific result struct.
func (r *LastRunRepository) Aggregate(ctx context.Context, pipeline mongo.Pipeline) (*mongo.Cursor, error) {
	return r.collection.Aggregate(ctx, pipeline)
}

// Watch creates a change stream to listen for real-time updates on this collection
func (r *LastRunRepository) Watch(ctx context.Context, pipeline mongo.Pipeline) (*mongo.ChangeStream, error) {
	return r.collection.Watch(ctx, pipeline)
}
