// Code generated by mongogen. DO NOT EDIT.
package model

import (
	"context"

	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

// LastRunRepository defines strict repository methods
type LastRunRepository struct {
	collection *mongo.Collection
}

// NewLastRunRepository creates a new repository instance
func NewLastRunRepository(db *mongo.Database) *LastRunRepository {
	return &LastRunRepository{
		collection: db.Collection("last_runs"),
	}
}

// --- Basic CRUD ---

// Create inserts a single LastRun
func (r *LastRunRepository) Create(ctx context.Context, model *LastRun, opts ...options.Lister[options.InsertOneOptions]) (*mongo.InsertOneResult, error) {
	return r.collection.InsertOne(ctx, model, opts...)
}

// CreateMany inserts multiple LastRun documents
func (r *LastRunRepository) CreateMany(ctx context.Context, models []*LastRun, opts ...options.Lister[options.InsertManyOptions]) (*mongo.InsertManyResult, error) {
	return r.collection.InsertMany(ctx, models, opts...)
}

// FindByID retrieves a document by its _id
func (r *LastRunRepository) FindByID(ctx context.Context, id bson.ObjectID) (*LastRun, error) {
	var model LastRun
	err := r.collection.FindOne(ctx, bson.M{"_id": id}).Decode(&model)
	if err != nil {
		return nil, err
	}
	return &model, nil
}

// FindOne retrieves a single document matching the filter
func (r *LastRunRepository) FindOne(ctx context.Context, filter bson.M, opts ...options.Lister[options.FindOneOptions]) (*LastRun, error) {
	var model LastRun
	err := r.collection.FindOne(ctx, filter, opts...).Decode(&model)
	if err != nil {
		return nil, err
	}
	return &model, nil
}

// UpdateByID updates a document by ID using the full update bson map (e.g., bson.M{"$set": fields} or bson.M{"$inc": ...})
func (r *LastRunRepository) UpdateByID(ctx context.Context, id bson.ObjectID, update bson.M, opts ...options.Lister[options.UpdateOneOptions]) (*mongo.UpdateResult, error) {
	return r.collection.UpdateOne(ctx, bson.M{"_id": id}, update, opts...)
}

// UpdateOne updates a single document matching the filter using the full update bson map
func (r *LastRunRepository) UpdateOne(ctx context.Context, filter bson.M, update bson.M, opts ...options.Lister[options.UpdateOneOptions]) (*mongo.UpdateResult, error) {
	return r.collection.UpdateOne(ctx, filter, update, opts...)
}

// UpdateMany updates multiple documents matching the filter using the full update bson map
func (r *LastRunRepository) UpdateMany(ctx context.Context, filter bson.M, update bson.M, opts ...options.Lister[options.UpdateManyOptions]) (*mongo.UpdateResult, error) {
	return r.collection.UpdateMany(ctx, filter, update, opts...)
}

// ReplaceOne replaces a single document matching the filter with the provided replacement
func (r *LastRunRepository) ReplaceOne(ctx context.Context, filter bson.M, replacement *LastRun, opts ...options.Lister[options.ReplaceOptions]) (*mongo.UpdateResult, error) {
	return r.collection.ReplaceOne(ctx, filter, replacement, opts...)
}

// DeleteByID removes a document by ID
func (r *LastRunRepository) DeleteByID(ctx context.Context, id bson.ObjectID, opts ...options.Lister[options.DeleteOneOptions]) (*mongo.DeleteResult, error) {
	return r.collection.DeleteOne(ctx, bson.M{"_id": id}, opts...)
}

// DeleteOne removes a single document matching the filter
func (r *LastRunRepository) DeleteOne(ctx context.Context, filter bson.M, opts ...options.Lister[options.DeleteOneOptions]) (*mongo.DeleteResult, error) {
	return r.collection.DeleteOne(ctx, filter, opts...)
}

// DeleteMany removes documents matching the filter
func (r *LastRunRepository) DeleteMany(ctx context.Context, filter bson.M, opts ...options.Lister[options.DeleteManyOptions]) (*mongo.DeleteResult, error) {
	return r.collection.DeleteMany(ctx, filter, opts...)
}

// --- Advanced Operations ---

// FindOneAndUpdate performs an atomic find and update operation
// Returns the *updated* document (ReturnDocument: After)
// update is the full update document, e.g., bson.M{"$set": fields} or bson.M{"$inc": ...}
func (r *LastRunRepository) FindOneAndUpdate(ctx context.Context, filter bson.M, update bson.M, opts ...options.Lister[options.FindOneAndUpdateOptions]) (*LastRun, error) {
	var model LastRun
	defaultOpts := options.FindOneAndUpdate().SetReturnDocument(options.After)
	combinedOpts := append([]options.Lister[options.FindOneAndUpdateOptions]{defaultOpts}, opts...)

	err := r.collection.FindOneAndUpdate(ctx, filter, update, combinedOpts...).Decode(&model)
	if err != nil {
		return nil, err
	}
	return &model, nil
}

// FindOneAndReplace performs an atomic find and replace operation
// Returns the *replaced* document (ReturnDocument: Before)
func (r *LastRunRepository) FindOneAndReplace(ctx context.Context, filter bson.M, replacement *LastRun, opts ...options.Lister[options.FindOneAndReplaceOptions]) (*LastRun, error) {
	var model LastRun
	defaultOpts := options.FindOneAndReplace().SetReturnDocument(options.Before)
	combinedOpts := append([]options.Lister[options.FindOneAndReplaceOptions]{defaultOpts}, opts...)

	err := r.collection.FindOneAndReplace(ctx, filter, replacement, combinedOpts...).Decode(&model)
	if err != nil {
		return nil, err
	}
	return &model, nil
}

// FindOneAndDelete performs an atomic find and delete operation
// Returns the *deleted* document
func (r *LastRunRepository) FindOneAndDelete(ctx context.Context, filter bson.M, opts ...options.Lister[options.FindOneAndDeleteOptions]) (*LastRun, error) {
	var model LastRun
	err := r.collection.FindOneAndDelete(ctx, filter, opts...).Decode(&model)
	if err != nil {
		return nil, err
	}
	return &model, nil
}

// Upsert updates a document if it exists, or creates it if it doesn't
// update is the full update document, e.g., bson.M{"$set": fields} or bson.M{"$inc": ...}
func (r *LastRunRepository) Upsert(ctx context.Context, id bson.ObjectID, update bson.M, opts ...options.Lister[options.UpdateOneOptions]) (*mongo.UpdateResult, error) {
	defaultOpts := options.UpdateOne().SetUpsert(true)
	combinedOpts := append([]options.Lister[options.UpdateOneOptions]{defaultOpts}, opts...)
	return r.collection.UpdateOne(ctx, bson.M{"_id": id}, update, combinedOpts...)
}

// UpsertOne upserts a single document matching the filter
func (r *LastRunRepository) UpsertOne(ctx context.Context, filter bson.M, update bson.M, opts ...options.Lister[options.UpdateOneOptions]) (*mongo.UpdateResult, error) {
	defaultOpts := options.UpdateOne().SetUpsert(true)
	combinedOpts := append([]options.Lister[options.UpdateOneOptions]{defaultOpts}, opts...)
	return r.collection.UpdateOne(ctx, filter, update, combinedOpts...)
}

// Count returns the number of documents matching a filter
func (r *LastRunRepository) Count(ctx context.Context, filter bson.M) (int64, error) {
	return r.collection.CountDocuments(ctx, filter)
}

// Distinct finds unique values for a specified field
func (r *LastRunRepository) Distinct(ctx context.Context, fieldName string, filter bson.M) (*mongo.DistinctResult, error) {
	res := r.collection.Distinct(ctx, fieldName, filter)
	return res, res.Err()
}

// Exists checks if a document exists by ID
func (r *LastRunRepository) Exists(ctx context.Context, id bson.ObjectID) (bool, error) {
	count, err := r.collection.CountDocuments(ctx, bson.M{"_id": id}, options.Count().SetLimit(1))
	return count > 0, err
}

// BulkWrite performs multiple write operations in bulk
func (r *LastRunRepository) BulkWrite(ctx context.Context, models []mongo.WriteModel, opts ...options.Lister[options.BulkWriteOptions]) (*mongo.BulkWriteResult, error) {
	return r.collection.BulkWrite(ctx, models, opts...)
}

// --- Search, Pagination & Aggregation ---

// FindAll retrieves all documents matching a filter
func (r *LastRunRepository) FindAll(ctx context.Context, filter bson.M, opts ...options.Lister[options.FindOptions]) ([]*LastRun, error) {
	cursor, err := r.collection.Find(ctx, filter, opts...)
	if err != nil {
		return nil, err
	}
	defer cursor.Close(ctx)

	var results []*LastRun
	if err = cursor.All(ctx, &results); err != nil {
		return nil, err
	}
	return results, nil
}

// Find returns a cursor for documents matching the filter
func (r *LastRunRepository) Find(ctx context.Context, filter bson.M, opts ...options.Lister[options.FindOptions]) (*mongo.Cursor, error) {
	return r.collection.Find(ctx, filter, opts...)
}

// FindPage retrieves a page of documents with sorting options
func (r *LastRunRepository) FindPage(ctx context.Context, filter bson.M, page int64, limit int64, sort bson.D, opts ...options.Lister[options.FindOptions]) ([]*LastRun, int64, error) {
	skip := (page - 1) * limit
	if skip < 0 {
		skip = 0
	}

	total, err := r.collection.CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, err
	}

	defaultOpts := options.Find().SetLimit(limit).SetSkip(skip).SetSort(sort)
	combinedOpts := append([]options.Lister[options.FindOptions]{defaultOpts}, opts...)

	cursor, err := r.collection.Find(ctx, filter, combinedOpts...)
	if err != nil {
		return nil, 0, err
	}
	defer cursor.Close(ctx)

	var results []*LastRun
	if err = cursor.All(ctx, &results); err != nil {
		return nil, 0, err
	}
	return results, total, nil
}

// Aggregate runs a raw aggregation pipeline
// Note: This returns a cursor because aggregation results usually do not match the LastRun structure.
// You must decode the cursor into your specific result struct.
func (r *LastRunRepository) Aggregate(ctx context.Context, pipeline mongo.Pipeline) (*mongo.Cursor, error) {
	return r.collection.Aggregate(ctx, pipeline)
}

// Watch creates a change stream to listen for real-time updates on this collection
func (r *LastRunRepository) Watch(ctx context.Context, pipeline mongo.Pipeline) (*mongo.ChangeStream, error) {
	return r.collection.Watch(ctx, pipeline)
}

// Collection returns the underlying mongo collection for advanced operations
func (r *LastRunRepository) Collection() *mongo.Collection {
	return r.collection
}
