// Code generated by mongogen. DO NOT EDIT.
package model

import (
	"context"

	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

// NewsRepository defines strict repository methods
type NewsRepository struct {
	collection *mongo.Collection
}

// NewNewsRepository creates a new repository instance
func NewNewsRepository(db *mongo.Database) *NewsRepository {
	return &NewsRepository{
		collection: db.Collection("news"),
	}
}

// --- Basic CRUD ---

// Create inserts a single News
func (r *NewsRepository) Create(ctx context.Context, model *News) (*mongo.InsertOneResult, error) {
	return r.collection.InsertOne(ctx, model)
}

// CreateMany inserts multiple News documents
func (r *NewsRepository) CreateMany(ctx context.Context, models []*News, opts ...options.Lister[options.InsertManyOptions]) (*mongo.InsertManyResult, error) {
	return r.collection.InsertMany(ctx, models, opts...)
}

// FindByID retrieves a document by its _id
func (r *NewsRepository) FindByID(ctx context.Context, id primitive.ObjectID) (*News, error) {
	var model News
	err := r.collection.FindOne(ctx, bson.M{"_id": id}).Decode(&model)
	if err != nil {
		return nil, err
	}
	return &model, nil
}

// FindOne retrieves a single document matching the filter
func (r *NewsRepository) FindOne(ctx context.Context, filter bson.M) (*News, error) {
	var model News
	err := r.collection.FindOne(ctx, filter).Decode(&model)
	if err != nil {
		return nil, err
	}
	return &model, nil
}

// UpdateByID updates a document by ID using the full update bson map (e.g., bson.M{"$set": fields} or bson.M{"$inc": ...})
func (r *NewsRepository) UpdateByID(ctx context.Context, id primitive.ObjectID, update bson.M) (*mongo.UpdateResult, error) {
	return r.collection.UpdateOne(ctx, bson.M{"_id": id}, update)
}

// UpdateOne updates a single document matching the filter using the full update bson map
func (r *NewsRepository) UpdateOne(ctx context.Context, filter bson.M, update bson.M, opts ...options.Lister[options.UpdateOneOptions]) (*mongo.UpdateResult, error) {
	return r.collection.UpdateOne(ctx, filter, update, opts...)
}

// UpdateMany updates multiple documents matching the filter using the full update bson map
func (r *NewsRepository) UpdateMany(ctx context.Context, filter bson.M, update bson.M, opts ...options.Lister[options.UpdateManyOptions]) (*mongo.UpdateResult, error) {
	return r.collection.UpdateMany(ctx, filter, update, opts...)
}

// ReplaceOne replaces a single document matching the filter with the provided replacement
func (r *NewsRepository) ReplaceOne(ctx context.Context, filter bson.M, replacement *News, opts ...options.Lister[options.ReplaceOptions]) (*mongo.UpdateResult, error) {
	return r.collection.ReplaceOne(ctx, filter, replacement, opts...)
}

// DeleteByID removes a document by ID
func (r *NewsRepository) DeleteByID(ctx context.Context, id primitive.ObjectID) (*mongo.DeleteResult, error) {
	return r.collection.DeleteOne(ctx, bson.M{"_id": id})
}

// DeleteOne removes a single document matching the filter
func (r *NewsRepository) DeleteOne(ctx context.Context, filter bson.M, opts ...options.Lister[options.DeleteOneOptions]) (*mongo.DeleteResult, error) {
	return r.collection.DeleteOne(ctx, filter, opts...)
}

// DeleteMany removes documents matching the filter
func (r *NewsRepository) DeleteMany(ctx context.Context, filter bson.M, opts ...options.Lister[options.DeleteManyOptions]) (*mongo.DeleteResult, error) {
	return r.collection.DeleteMany(ctx, filter, opts...)
}

// --- Advanced Operations ---

// FindOneAndUpdate performs an atomic find and update operation
// Returns the *updated* document (ReturnDocument: After)
// update is the full update document, e.g., bson.M{"$set": fields} or bson.M{"$inc": ...}
func (r *NewsRepository) FindOneAndUpdate(ctx context.Context, filter bson.M, update bson.M) (*News, error) {
	var model News
	opts := options.FindOneAndUpdate().SetReturnDocument(options.After)

	err := r.collection.FindOneAndUpdate(ctx, filter, update, opts).Decode(&model)
	if err != nil {
		return nil, err
	}
	return &model, nil
}

// FindOneAndReplace performs an atomic find and replace operation
// Returns the *replaced* document (ReturnDocument: Before)
func (r *NewsRepository) FindOneAndReplace(ctx context.Context, filter bson.M, replacement *News, opts ...options.Lister[options.FindOneAndReplaceOptions]) (*News, error) {
	var model News
	defaultOpts := options.FindOneAndReplace().SetReturnDocument(options.Before)
	combinedOpts := append([]options.Lister[options.FindOneAndReplaceOptions]{defaultOpts}, opts...)

	err := r.collection.FindOneAndReplace(ctx, filter, replacement, combinedOpts...).Decode(&model)
	if err != nil {
		return nil, err
	}
	return &model, nil
}

// FindOneAndDelete performs an atomic find and delete operation
// Returns the *deleted* document
func (r *NewsRepository) FindOneAndDelete(ctx context.Context, filter bson.M, opts ...options.Lister[options.FindOneAndDeleteOptions]) (*News, error) {
	var model News
	err := r.collection.FindOneAndDelete(ctx, filter, opts...).Decode(&model)
	if err != nil {
		return nil, err
	}
	return &model, nil
}

// Upsert updates a document if it exists, or creates it if it doesn't
// update is the full update document, e.g., bson.M{"$set": fields} or bson.M{"$inc": ...}
func (r *NewsRepository) Upsert(ctx context.Context, id primitive.ObjectID, update bson.M) (*mongo.UpdateResult, error) {
	opts := options.UpdateOne().SetUpsert(true)
	return r.collection.UpdateOne(ctx, bson.M{"_id": id}, update, opts)
}

// Count returns the number of documents matching a filter
func (r *NewsRepository) Count(ctx context.Context, filter bson.M) (int64, error) {
	return r.collection.CountDocuments(ctx, filter)
}

// Distinct finds unique values for a specified field
func (r *NewsRepository) Distinct(ctx context.Context, fieldName string, filter bson.M) (*mongo.DistinctResult, error) {
	res := r.collection.Distinct(ctx, fieldName, filter)
	return res, res.Err()
}

// BulkWrite performs multiple write operations in bulk
func (r *NewsRepository) BulkWrite(ctx context.Context, models []mongo.WriteModel, opts ...options.Lister[options.BulkWriteOptions]) (*mongo.BulkWriteResult, error) {
	return r.collection.BulkWrite(ctx, models, opts...)
}

// --- Search, Pagination & Aggregation ---

// FindAll retrieves all documents matching a filter
func (r *NewsRepository) FindAll(ctx context.Context, filter bson.M) ([]*News, error) {
	cursor, err := r.collection.Find(ctx, filter)
	if err != nil {
		return nil, err
	}
	defer cursor.Close(ctx)

	var results []*News
	if err = cursor.All(ctx, &results); err != nil {
		return nil, err
	}
	return results, nil
}

// FindPage retrieves a page of documents with sorting options
func (r *NewsRepository) FindPage(ctx context.Context, filter bson.M, page int64, limit int64, sort interface{}) ([]*News, int64, error) {
	skip := (page - 1) * limit
	if skip < 0 {
		skip = 0
	}

	total, err := r.collection.CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, err
	}

	opts := options.Find().SetLimit(limit).SetSkip(skip).SetSort(sort)
	cursor, err := r.collection.Find(ctx, filter, opts)
	if err != nil {
		return nil, 0, err
	}
	defer cursor.Close(ctx)

	var results []*News
	if err = cursor.All(ctx, &results); err != nil {
		return nil, 0, err
	}
	return results, total, nil
}

// Aggregate runs a raw aggregation pipeline
// Note: This returns a cursor because aggregation results usually do not match the News structure.
// You must decode the cursor into your specific result struct.
func (r *NewsRepository) Aggregate(ctx context.Context, pipeline mongo.Pipeline) (*mongo.Cursor, error) {
	return r.collection.Aggregate(ctx, pipeline)
}

// Watch creates a change stream to listen for real-time updates on this collection
func (r *NewsRepository) Watch(ctx context.Context, pipeline mongo.Pipeline) (*mongo.ChangeStream, error) {
	return r.collection.Watch(ctx, pipeline)
}
