paths:
  browser_profile: /tmp
  check_dir: /tmp
  download_dir: /tmp
  issuer_list: /dev/null

mailing:
  sender_email: example@gmail.com
  sender_password: your_email_password
  mailing_list:
    - test@example.com

database:
  uri: mongodb://localhost:27017
  db_name: yourdbname

download:
  year: 2023
  mode: TW
  month_period: 3

openrouter_api_key: your_api_key_here
