package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"strings"
	"text/template"
)

// Config holds the data used to populate the template
type Config struct {
	PackageName string
	StructName  string
	TableName   string
}

var outputTemplate = `
// Code generated by mongogen. DO NOT EDIT.
package {{.PackageName}}

import (
	"context"

	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

// {{.StructName}}Repository defines strict repository methods
type {{.StructName}}Repository struct {
	collection *mongo.Collection
}

// New{{.StructName}}Repository creates a new repository instance
func New{{.StructName}}Repository(db *mongo.Database) *{{.StructName}}Repository {
	return &{{.StructName}}Repository{
		collection: db.Collection("{{.TableName}}"),
	}
}

// --- Basic CRUD ---

// Create inserts a single {{.StructName}}
func (r *{{.StructName}}Repository) Create(ctx context.Context, model *{{.StructName}}) (*mongo.InsertOneResult, error) {
	return r.collection.InsertOne(ctx, model)
}

// CreateMany inserts multiple {{.StructName}} documents
func (r *{{.StructName}}Repository) CreateMany(ctx context.Context, models []*{{.StructName}}, opts ...options.Lister[options.InsertManyOptions]) (*mongo.InsertManyResult, error) {
	return r.collection.InsertMany(ctx, models, opts...)
}

// FindByID retrieves a document by its _id
func (r *{{.StructName}}Repository) FindByID(ctx context.Context, id primitive.ObjectID) (*{{.StructName}}, error) {
	var model {{.StructName}}
	err := r.collection.FindOne(ctx, bson.M{"_id": id}).Decode(&model)
	if err != nil {
		return nil, err
	}
	return &model, nil
}

// FindOne retrieves a single document matching the filter
func (r *{{.StructName}}Repository) FindOne(ctx context.Context, filter bson.M) (*{{.StructName}}, error) {
	var model {{.StructName}}
	err := r.collection.FindOne(ctx, filter).Decode(&model)
	if err != nil {
		return nil, err
	}
	return &model, nil
}

// UpdateByID updates a document by ID using the full update bson map (e.g., bson.M{"$set": fields} or bson.M{"$inc": ...})
func (r *{{.StructName}}Repository) UpdateByID(ctx context.Context, id primitive.ObjectID, update bson.M) (*mongo.UpdateResult, error) {
	return r.collection.UpdateOne(ctx, bson.M{"_id": id}, update)
}

// UpdateOne updates a single document matching the filter using the full update bson map
func (r *{{.StructName}}Repository) UpdateOne(ctx context.Context, filter bson.M, update bson.M, opts ...options.Lister[options.UpdateOneOptions]) (*mongo.UpdateResult, error) {
	return r.collection.UpdateOne(ctx, filter, update, opts...)
}

// UpdateMany updates multiple documents matching the filter using the full update bson map
func (r *{{.StructName}}Repository) UpdateMany(ctx context.Context, filter bson.M, update bson.M, opts ...options.Lister[options.UpdateManyOptions]) (*mongo.UpdateResult, error) {
	return r.collection.UpdateMany(ctx, filter, update, opts...)
}

// ReplaceOne replaces a single document matching the filter with the provided replacement
func (r *{{.StructName}}Repository) ReplaceOne(ctx context.Context, filter bson.M, replacement *{{.StructName}}, opts ...options.Lister[options.ReplaceOptions]) (*mongo.UpdateResult, error) {
	return r.collection.ReplaceOne(ctx, filter, replacement, opts...)
}

// DeleteByID removes a document by ID
func (r *{{.StructName}}Repository) DeleteByID(ctx context.Context, id primitive.ObjectID) (*mongo.DeleteResult, error) {
	return r.collection.DeleteOne(ctx, bson.M{"_id": id})
}

// DeleteOne removes a single document matching the filter
func (r *{{.StructName}}Repository) DeleteOne(ctx context.Context, filter bson.M, opts ...options.Lister[options.DeleteOneOptions]) (*mongo.DeleteResult, error) {
	return r.collection.DeleteOne(ctx, filter, opts...)
}

// DeleteMany removes documents matching the filter
func (r *{{.StructName}}Repository) DeleteMany(ctx context.Context, filter bson.M, opts ...options.Lister[options.DeleteManyOptions]) (*mongo.DeleteResult, error) {
	return r.collection.DeleteMany(ctx, filter, opts...)
}

// --- Advanced Operations ---

// FindOneAndUpdate performs an atomic find and update operation
// Returns the *updated* document (ReturnDocument: After)
// update is the full update document, e.g., bson.M{"$set": fields} or bson.M{"$inc": ...}
func (r *{{.StructName}}Repository) FindOneAndUpdate(ctx context.Context, filter bson.M, update bson.M) (*{{.StructName}}, error) {
	var model {{.StructName}}
	opts := options.FindOneAndUpdate().SetReturnDocument(options.After)

	err := r.collection.FindOneAndUpdate(ctx, filter, update, opts).Decode(&model)
	if err != nil {
		return nil, err
	}
	return &model, nil
}

// FindOneAndReplace performs an atomic find and replace operation
// Returns the *replaced* document (ReturnDocument: Before)
func (r *{{.StructName}}Repository) FindOneAndReplace(ctx context.Context, filter bson.M, replacement *{{.StructName}}, opts ...options.Lister[options.FindOneAndReplaceOptions]) (*{{.StructName}}, error) {
	var model {{.StructName}}
	defaultOpts := options.FindOneAndReplace().SetReturnDocument(options.Before)
	combinedOpts := append([]options.Lister[options.FindOneAndReplaceOptions]{defaultOpts}, opts...)

	err := r.collection.FindOneAndReplace(ctx, filter, replacement, combinedOpts...).Decode(&model)
	if err != nil {
		return nil, err
	}
	return &model, nil
}

// FindOneAndDelete performs an atomic find and delete operation
// Returns the *deleted* document
func (r *{{.StructName}}Repository) FindOneAndDelete(ctx context.Context, filter bson.M, opts ...options.Lister[options.FindOneAndDeleteOptions]) (*{{.StructName}}, error) {
	var model {{.StructName}}
	err := r.collection.FindOneAndDelete(ctx, filter, opts...).Decode(&model)
	if err != nil {
		return nil, err
	}
	return &model, nil
}

// Upsert updates a document if it exists, or creates it if it doesn't
// update is the full update document, e.g., bson.M{"$set": fields} or bson.M{"$inc": ...}
func (r *{{.StructName}}Repository) Upsert(ctx context.Context, id primitive.ObjectID, update bson.M) (*mongo.UpdateResult, error) {
	opts := options.UpdateOne().SetUpsert(true)
	return r.collection.UpdateOne(ctx, bson.M{"_id": id}, update, opts)
}

// Count returns the number of documents matching a filter
func (r *{{.StructName}}Repository) Count(ctx context.Context, filter bson.M) (int64, error) {
	return r.collection.CountDocuments(ctx, filter)
}

// Distinct finds unique values for a specified field
func (r *{{.StructName}}Repository) Distinct(ctx context.Context, fieldName string, filter bson.M) (*mongo.DistinctResult, error) {
	res := r.collection.Distinct(ctx, fieldName, filter)
	return res, res.Err()
}

// BulkWrite performs multiple write operations in bulk
func (r *{{.StructName}}Repository) BulkWrite(ctx context.Context, models []mongo.WriteModel, opts ...options.Lister[options.BulkWriteOptions]) (*mongo.BulkWriteResult, error) {
	return r.collection.BulkWrite(ctx, models, opts...)
}

// --- Search, Pagination & Aggregation ---

// FindAll retrieves all documents matching a filter
func (r *{{.StructName}}Repository) FindAll(ctx context.Context, filter bson.M) ([]*{{.StructName}}, error) {
	cursor, err := r.collection.Find(ctx, filter)
	if err != nil {
		return nil, err
	}
	defer cursor.Close(ctx)

	var results []*{{.StructName}}
	if err = cursor.All(ctx, &results); err != nil {
		return nil, err
	}
	return results, nil
}

// FindPage retrieves a page of documents with sorting options
func (r *{{.StructName}}Repository) FindPage(ctx context.Context, filter bson.M, page int64, limit int64, sort interface{}) ([]*{{.StructName}}, int64, error) {
	skip := (page - 1) * limit
	if skip < 0 {
		skip = 0
	}

	total, err := r.collection.CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, err
	}

	opts := options.Find().SetLimit(limit).SetSkip(skip).SetSort(sort)
	cursor, err := r.collection.Find(ctx, filter, opts)
	if err != nil {
		return nil, 0, err
	}
	defer cursor.Close(ctx)

	var results []*{{.StructName}}
	if err = cursor.All(ctx, &results); err != nil {
		return nil, 0, err
	}
	return results, total, nil
}

// Aggregate runs a raw aggregation pipeline
// Note: This returns a cursor because aggregation results usually do not match the {{.StructName}} structure.
// You must decode the cursor into your specific result struct.
func (r *{{.StructName}}Repository) Aggregate(ctx context.Context, pipeline mongo.Pipeline) (*mongo.Cursor, error) {
	return r.collection.Aggregate(ctx, pipeline)
}

// Watch creates a change stream to listen for real-time updates on this collection
func (r *{{.StructName}}Repository) Watch(ctx context.Context, pipeline mongo.Pipeline) (*mongo.ChangeStream, error) {
	return r.collection.Watch(ctx, pipeline)
}
`

func main() {
	// Parse flags
	typePtr := flag.String("type", "", "The struct name to generate code for")
	collectionPtr := flag.String("collection", "", "The mongodb collection name (optional, defaults to lowercase struct name)")
	flag.Parse()

	if *typePtr == "" {
		log.Fatal("type argument is required")
	}

	// Gather environment info provided by go generate
	pkg := os.Getenv("GOPACKAGE")
	if pkg == "" {
		log.Fatal("GOPACKAGE environment variable not set")
	}

	col := *collectionPtr
	if col == "" {
		col = strings.ToLower(*typePtr) + "s"
	}

	config := Config{
		PackageName: pkg,
		StructName:  *typePtr,
		TableName:   col,
	}

	// Execute Template
	t, err := template.New("mongo").Parse(outputTemplate)
	if err != nil {
		log.Fatal(err)
	}

	var buf bytes.Buffer
	err = t.Execute(&buf, config)
	if err != nil {
		log.Fatal(err)
	}

	// Format the code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("formatting error: %s", err)
	}

	// Write to file
	filename := fmt.Sprintf("%s_mongo.go", strings.ToLower(*typePtr))
	err = os.WriteFile(filename, formatted, 0644)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("Generated %s for struct %s\n", filename, *typePtr)
}
